config/routes.rb
Rails.application.routes.draw do
  resources :departments
  resources :products, only: [:new, :create, :destroy, :edit, :update]
  get "/products/search" => "products#search", as: :search_product
  root "products#index"
end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :department

  validates :quantity, presence: true
  validates :name, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: [:edit, :update, :destroy]

  def index
    @productsByName = Product.order(:name).limit 5
    @productsByPrice = Product.order(:price).limit 2
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:notice] = "Produto salvo com sucesso"
      redirect_to root_url
    else
      render :new
    end
  end

  def new
    @product = Product.new
    render_page :new
  end

  def destroy
    @product.destroy
    redirect_to root_url
  end

  def search
    @name_to_search = params[:nome]
    @products = Product.where "name like ?", "%#{@name_to_search}%"
  end

  def edit
    render_page :edit
  end

  def update
    if @product.update product_params
      flash[:notice] = "Produto atualizado com sucesso"
      redirect_to root_url
    else
      render_page :new
    end
  end

  private

  def set_product
    id = params[:id]
    @product = Product.find(id)
  end

  def render_page(view)
    @departments = Department.all
    render view
  end

  def product_params
    params.require(:product).permit(:name, :description, :quantity, :price, :department_id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lojadecamisetas</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= nav_bar brand: "Calaio", brand_link: root_url do %>
    <%= form_tag search_product_path, method: :get, class: "navbar-form navbar-right" do %>
        <div class="form-group">
          <%= text_field_tag :nome, @name_to_search, class: "form-control" %>
          <%= button_to "Buscar", nil, class: "btn btn-default" %>
        </div>
    <% end %>
<% end %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/products/_form.html.erb
<% @product.errors.full_messages.each do |message| %>
    <div class="alert alert-danger" role="alert">
      <%= message %>
    </div>
<% end %>

<%= form_for @product do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <br>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control", rows: 4 %>
    </div>

    <div class="form-group">
      <%= f.label :department %>
      <%= f.collection_select :department_id, @departments, :id, :name, {}, class: "form-control" %>
    </div>

    <br>
    <div class="form-inline">
      <div class="form-group">
        <%= f.label :quantity %>
        <%= f.number_field :quantity, step: 1 %>
      </div>

      <div class="form-group">
        <%= f.label :price %>
        <%= f.number_field :price, step: 0.1 %>
      </div>
      <%= f.submit text_action, class: "btn btn-primary" %>
    </div>


<% end %>

app/views/products/_product.html.erb
<tr>
  <td> <%= product.name %> </td>
  <td> <%= product.description %></td>
  <td> <%= product.price %></td>
  <td>
    <%= link_to "Alterar", edit_product_path(product), class: "btn btn-default" %>
    <%= button_to "Remover", product, method: :delete, class: "btn btn-danger",
                  data: {confirm: "Tem certeza que deseja remover o produto: #{product.name}?"} %>
  </td>
</tr>

app/views/products/edit.html.erb
<%= render partial: 'form', locals: {text_action: 'Atualizar o produto'} %>

app/views/products/index.erb
<!DOCTYPE html>
<html>
<head>
	<title>Teste</title>
</head>
<body>
<%= nav_bar brand: "Calaio", brand_link: root_url %>
<table class="table table-bordered">
	<thead>
		<tr>
			<th>Nome</th>
			<th>Descrição</th>
			<th>Preço</th>
			<th>Quantidade</th>
		</tr>
	</thead>
	<tbody>
		<% @productsByName.each do |product| %>
		<tr>
			<td> <%= product.name %> </td>
			<td> <%= product.description %></td>
			<td> <%= product.quantity %></td>
			<td> <%= product.price %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<table class="table table-bordered">
	<thead>
		<tr>
			<th>Nome</th>
			<th>Descrição</th>
			<th>Preço</th>
			<th>Quantidade</th>
		</tr>
	</thead>
	<tbody>
		<% @productsByPrice.each do |product| %>
		<tr>
			<td> <%= product.name %> </td>
			<td> <%= product.description %></td>
			<td> <%= product.quantity %></td>
			<td> <%= product.price %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</body>
</html>

app/views/products/index.html.erb
<% if flash[:notice] %>
<div class="alert alert-success" role="alert">
  <%= flash[:notice] %>
</div>
    <% end %>

<table class="table table-bordered">
  <thead>
  <tr>
    <th>Nome</th>
    <th>Descrição</th>
    <th>Preço</th>
    <th>Opção</th>
  </tr>
  </thead>
  <tbody>
      <%= render @productsByName %>
  </tbody>
</table>

<table class="table table-bordered">
  <thead>
  <tr>
    <th>Nome</th>
    <th>Descrição</th>
    <th>Preço</th>
  </tr>
  </thead>
  <tbody>
      <%= render @productsByPrice %>
  </tbody>
</table>


<%= link_to "Criar produto", new_product_path %>

app/views/products/new.html.erb
<%= render partial: 'form', locals: {text_action: 'Criar o produto'} %>

app/views/products/search.html.erb
<table class="table table-bordered">
  <thead>
  <tr>
    <th>Nome</th>
    <th>Descrição</th>
    <th>Preço</th>
    <th>Opção</th>
  </tr>
  </thead>
  <tbody>
    <%= render @products %>
  </tbody>
</table>